title: Jamios Mission Framework
description: A mission framework for the Misfits Arma 3 Group
theme: just-the-docs

url: https://jamio.github.io/JM_MissionFrameworkDocs/

aux_links:
  Template Repository: https://github.com/Jamio/JM_MissionFrameworkDocs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

